# Generated by Django 2.0.4 on 2018-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
